### ISSUE TITLE
COCO skeleton connection

### ISSUE THREAD

**Issue by HiAleeYang** [stefanopini/simple-HigherHRNet#11]
https://github.com/stefanopini/simple-HigherHRNet/blob/59ece4a24c24cc6947ceb23f49f1a413c8837bfd/misc/visualization.py#L38
why do you use [0, 5], [0, 6] instead of  [3, 5], [4, 6]？

**Comment by stefanopini** [comment]
Hi! I chose the nose-shoulder links instead of the ear-shoulder ones after having tried both for a personal preference.
It only affects visualization so you can change them if you prefer the latter over the former.
https://github.com/stefanopini/simple-HigherHRNet/blob/59ece4a24c24cc6947ceb23f49f1a413c8837bfd/misc/visualization.py#L37-L38
