### ISSUE TITLE
How to train for multi-person detection?

### ISSUE THREAD

**Issue by OOF-dura** [stefanopini/simple-HigherHRNet#7]
I have a dataset which is with skeleton annotations. 
However, there are multi-person. Not single person.
How can I train this?

I do not want to first detect the bounding box of the person.

**Comment by stefanopini** [comment]
Hi!

As I reported in Issue #5 , I'm sorry I'm not planning to implement and release the training code for HigherHRNet because the results and the inference speed are quite disappointing with respect to HRNet.

You may have a look at the [official implementation](https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation), which includes a training script for COCO, and try to adapt the Dataset class to work with your data.
